# Stubs MicroPython para el analizador (time de CPython no tiene ticks_*).

def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_diff(t1: int, t2: int) -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...
def sleep(seconds: float) -> None: ...
